import { Sun, Battery, Plug, Building2, Home, Award } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const SolarSystem = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-grow pt-32">
        <div className="bg-gradient-to-r from-[#1A3C2F] to-[#2A5C4F] text-white py-16">
          <div className="container mx-auto px-4">
            <h1 className="text-4xl md:text-5xl font-bold mb-6">Solar PV Panels</h1>
            <p className="text-xl mb-8">A Cost-Effective Solution for Modern Energy Needs</p>
          </div>
        </div>

        <div className="container mx-auto px-4 py-16">
          <div className="grid md:grid-cols-2 gap-12 items-center mb-16">
            <div>
              <p className="text-lg text-gray-700 mb-8">
                Solar photovoltaic (PV) panels are an efficient and affordable way to meet energy demands today. 
                A photovoltaic module is a packaged assembly of solar cells combined with a charge controller 
                and an output socket. These panels can be used in large megawatt (MW) scale power plants as 
                well as for powering personal and home appliances. Panel sizes typically range from 1W to 550W per panel.
              </p>
              <div className="bg-white rounded-lg shadow-lg p-8">
                <h2 className="text-2xl font-bold mb-6">Types of Solar Rooftop Systems</h2>
                <div className="space-y-6">
                  <div className="flex items-start gap-3">
                    <Battery className="text-primary mt-1 flex-shrink-0" />
                    <div>
                      <h3 className="font-semibold mb-2">Solar Rooftop System with Storage Facility (OFFGRID)</h3>
                      <p>These systems use batteries to store energy, ensuring power availability even during non-sunny periods.</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <Plug className="text-primary mt-1 flex-shrink-0" />
                    <div>
                      <h3 className="font-semibold mb-2">Grid-Connected Solar Rooftop System (ONGRID)</h3>
                      <p>The DC power generated by the solar PV panels is converted to AC power using an inverter and fed to the grid via:</p>
                      <ul className="list-disc ml-6 mt-2">
                        <li>33 kV/11 kV three-phase lines (for larger capacities)</li>
                        <li>440/220 Volt three/single-phase lines (for smaller installations)</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="rounded-lg overflow-hidden shadow-xl">
              <img 
                src="/lovable-uploads/5f06c520-cd37-4c0d-8a2a-1d0ae906112c.png" 
                alt="Solar System" 
                className="w-full h-[500px] object-cover"
              />
            </div>
          </div>

          <div className="bg-gray-50 rounded-lg p-8 mb-16">
            <h2 className="text-3xl font-bold mb-8">Key Features of ONGRID Systems</h2>
            <div className="grid md:grid-cols-3 gap-8">
              <div className="bg-white p-6 rounded-lg shadow-md">
                <Sun className="text-primary w-12 h-12 mb-4" />
                <h3 className="text-xl font-semibold mb-3">Daytime Power Generation</h3>
                <p>Power generated during the day is fully utilized to meet on-site energy needs.</p>
              </div>
              <div className="bg-white p-6 rounded-lg shadow-md">
                <Plug className="text-primary w-12 h-12 mb-4" />
                <h3 className="text-xl font-semibold mb-3">Excess Power Supply</h3>
                <p>Surplus power is fed into the grid as long as the grid is available.</p>
              </div>
              <div className="bg-white p-6 rounded-lg shadow-md">
                <Battery className="text-primary w-12 h-12 mb-4" />
                <h3 className="text-xl font-semibold mb-3">Power Backup from Grid</h3>
                <p>Seamless grid power supply during insufficient solar generation.</p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-lg p-8">
            <h2 className="text-3xl font-bold mb-8 text-center">Who We Are</h2>
            <p className="text-lg text-gray-700 mb-8 text-center">
              We are one of the oldest solar power plant suppliers based in Tamil Nadu, offering turnkey 
              solar solutions across South India.
            </p>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-gray-50 p-6 rounded-lg">
                <Home className="text-primary w-12 h-12 mb-4" />
                <h3 className="text-xl font-semibold mb-3">Domestic Rooftop Solar Power Plants</h3>
                <p>Capacities ranging from 2 kW to 25 kW for residential use.</p>
              </div>
              <div className="bg-gray-50 p-6 rounded-lg">
                <Building2 className="text-primary w-12 h-12 mb-4" />
                <h3 className="text-xl font-semibold mb-3">Grid-Connected Solar Power Plants</h3>
                <p>Tailored for commercial and investment purposes, with capacities ranging from 25 kW to 3 MW.</p>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default SolarSystem;
