import ServiceLayout from "@/components/services/ServiceLayout";
import { Battery, Sun, Plug } from "lucide-react";

const SolarSystem = () => {
  return (
    <ServiceLayout
      title="Solar PV Panels"
      description="A Cost-Effective Solution for Modern Energy Needs. Solar photovoltaic (PV) panels are an efficient and affordable way to meet energy demands today."
      imageUrl="https://images.unsplash.com/photo-1509391366360-2e959784a276"
      features={[
        "Photovoltaic module with integrated charge controller",
        "Panel sizes from 1W to 550W",
        "Suitable for MW scale power plants",
        "Residential and commercial applications",
        "Grid-connected options available"
      ]}
      benefits={[
        "Significant reduction in electricity bills",
        "Reliable power generation",
        "Low maintenance requirements",
        "Environmental sustainability",
        "Long-term cost savings"
      ]}
    >
      <div className="space-y-12">
        <section>
          <h2 className="text-3xl font-bold mb-6">Types of Solar Rooftop Systems</h2>
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-white p-6 rounded-lg shadow-lg">
              <div className="flex items-center gap-3 mb-4">
                <Battery className="text-primary w-8 h-8" />
                <h3 className="text-xl font-semibold">Off-Grid System (With Storage)</h3>
              </div>
              <p className="text-gray-700">
                These systems use batteries to store energy, ensuring power availability even during non-sunny periods.
              </p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow-lg">
              <div className="flex items-center gap-3 mb-4">
                <Plug className="text-primary w-8 h-8" />
                <h3 className="text-xl font-semibold">On-Grid System</h3>
              </div>
              <p className="text-gray-700">
                DC power generated by solar PV panels is converted to AC power using an inverter and fed to the grid via 33 kV/11 kV three-phase lines or 440/220 Volt lines.
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-6">Key Features of ONGRID Systems</h2>
          <ul className="space-y-4">
            <li className="flex items-start gap-3">
              <Sun className="text-primary mt-1 flex-shrink-0" />
              <span className="text-gray-700">Daytime Power Generation: Power generated during the day is fully utilized to meet on-site energy needs.</span>
            </li>
            <li className="flex items-start gap-3">
              <Sun className="text-primary mt-1 flex-shrink-0" />
              <span className="text-gray-700">Excess Power Supply: Surplus power is fed into the grid as long as the grid is available.</span>
            </li>
            <li className="flex items-start gap-3">
              <Sun className="text-primary mt-1 flex-shrink-0" />
              <span className="text-gray-700">Power Backup from Grid: Seamless grid power supply during insufficient solar generation.</span>
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-3xl font-bold mb-6">Who We Are</h2>
          <div className="bg-gray-50 p-8 rounded-lg">
            <p className="text-lg text-gray-700 mb-6">
              We are one of the oldest solar power plant suppliers based in Tamil Nadu, offering turnkey solar solutions across South India.
            </p>
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-white p-6 rounded-lg shadow">
                <h3 className="text-xl font-semibold mb-4">Domestic Rooftop Solar Power Plants</h3>
                <p className="text-gray-700">Capacities ranging from 2 kW to 25 kW for residential use.</p>
              </div>
              <div className="bg-white p-6 rounded-lg shadow">
                <h3 className="text-xl font-semibold mb-4">Grid-Connected Solar Power Plants</h3>
                <p className="text-gray-700">Tailored for commercial and investment purposes, with capacities ranging from 25 kW to 3 MW.</p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </ServiceLayout>
  );
};

export default SolarSystem;